### ISSUE TITLE
Failed to open window on some examples

### ISSUE THREAD

**Issue by stuaxo** [progschj/OpenGL-Examples#6]
I reckon this is because it's not getting the opengl version it wants, any chance of some more error reporting ?

These ones got the error:

```
./11tesselation
./12shader_image_load_store
./13compute_shader_nbody
```

BTW, these are all all very nice examples :)

**Comment by progschj** [comment]
Yes, those three require OpenGL versions of 4 and higher (4.3 for compute shaders for example). I guess it would be reasonable to add something "(this is most likely caused by an unsupported OpenGL version number)". The problem I think is that the underlying apis/wrappers don't actually give you any information outside of failed context creation. As far as I'm aware there is no a priori way to find the max supported version. You can just try and see if it fails.

**Comment by stuaxo** [comment]
Ah, thats fine - I've been following mesamatrix to see what should be supported, hopefully 4.3 will not take too long :)
